name: Synchronize Ecom-services Labels
on:
  #pull_request:
  # types:
  #  - synchronize
  # - closed
  push:
    branches:
      - lokalise
env:
  label_paths: ("web/insightweb/src/main/webapp/assets")

jobs:
  Synchronize-labels:
    name: Synchronize
    #if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Checkout ecom-services
        uses: actions/checkout@v2
        with:
          repository: Insight-IT-Web/ecom-services
          path: ecom-services
          ref: lokalise
          clean: true
          token: ${{ secrets.WEB_TO_LOKALISE }}
      - name: Synchronize ecom-services labels
        run: |
          labels_paths=${{ env.label_paths }} 
          for label_path in "${labels_paths[@]}" 
          do
          echo "$label_path"
            if [ -d ecom-services/$label_path/labels ]; then
             rm -Rf ecom-services/$label_path/labels
            fi
            mkdir -p ecom-services/$label_path/labels
            echo "i am herE"
           cp -R  $label_path/labels ecom-services/$label_path/
          done
          cd label_path
          git remote set-url origin https://${{ secrets.WEB_TO_LOKALISE }}@github.com/Insight-IT-Web/ecom-services.git
          git config --global user.email "pjetly@insight.com"
          git config --global user.name "Pooja jetly"
          git status
          git add .
          git status
          git commit -m "PRT-1234 synchronizing ecom-services labels"
          git push
        shell: bash
